apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: sweatsync
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: sweatsync
  DATABASE_URL: postgresql://user:password@postgres:5432/sweatsync
